/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.polysfactory.robotaudio.jni;

public interface NativeSoundTouchConstants {
  public final static String SOUNDTOUCH_VERSION = NativeSoundTouchJNI.SOUNDTOUCH_VERSION_get();
  public final static int SOUNDTOUCH_VERSION_ID = NativeSoundTouchJNI.SOUNDTOUCH_VERSION_ID_get();
  public final static int SETTING_USE_AA_FILTER = NativeSoundTouchJNI.SETTING_USE_AA_FILTER_get();
  public final static int SETTING_AA_FILTER_LENGTH = NativeSoundTouchJNI.SETTING_AA_FILTER_LENGTH_get();
  public final static int SETTING_USE_QUICKSEEK = NativeSoundTouchJNI.SETTING_USE_QUICKSEEK_get();
  public final static int SETTING_SEQUENCE_MS = NativeSoundTouchJNI.SETTING_SEQUENCE_MS_get();
  public final static int SETTING_SEEKWINDOW_MS = NativeSoundTouchJNI.SETTING_SEEKWINDOW_MS_get();
  public final static int SETTING_OVERLAP_MS = NativeSoundTouchJNI.SETTING_OVERLAP_MS_get();
  public final static int SETTING_NOMINAL_INPUT_SEQUENCE = NativeSoundTouchJNI.SETTING_NOMINAL_INPUT_SEQUENCE_get();
  public final static int SETTING_NOMINAL_OUTPUT_SEQUENCE = NativeSoundTouchJNI.SETTING_NOMINAL_OUTPUT_SEQUENCE_get();
  public final static int BUFF_SIZE = NativeSoundTouchJNI.BUFF_SIZE_get();
}
