/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.polysfactory.robotaudio.jni;

//import com.opencv.jni.*; //import the android-opencv jni wrappers

public class NativeSoundTouchJNI {

	static {
		try {
			//load the cvcamera library, make sure that libcvcamera.so is in your <project>/libs/armeabi directory
			//so that android sdk automatically installs it along with the app.
			
			//the android-opencv lib must be loaded first inorder for the cvcamera
			//lib to be found
			//check the apk generated, by opening it in an archive manager, to verify that
			//both these libraries are present
			System.loadLibrary("SoundTouch");
		} catch (UnsatisfiedLinkError e) {
			//badness
			throw e;
		}
	}


  public final static native String SOUNDTOUCH_VERSION_get();
  public final static native int SOUNDTOUCH_VERSION_ID_get();
  public final static native int SETTING_USE_AA_FILTER_get();
  public final static native int SETTING_AA_FILTER_LENGTH_get();
  public final static native int SETTING_USE_QUICKSEEK_get();
  public final static native int SETTING_SEQUENCE_MS_get();
  public final static native int SETTING_SEEKWINDOW_MS_get();
  public final static native int SETTING_OVERLAP_MS_get();
  public final static native int SETTING_NOMINAL_INPUT_SEQUENCE_get();
  public final static native int SETTING_NOMINAL_OUTPUT_SEQUENCE_get();
  public final static native long new_SoundTouch();
  public final static native void delete_SoundTouch(long jarg1);
  public final static native String SoundTouch_getVersionString();
  public final static native long SoundTouch_getVersionId();
  public final static native void SoundTouch_setRate(long jarg1, SoundTouch jarg1_, float jarg2);
  public final static native void SoundTouch_setTempo(long jarg1, SoundTouch jarg1_, float jarg2);
  public final static native void SoundTouch_setRateChange(long jarg1, SoundTouch jarg1_, float jarg2);
  public final static native void SoundTouch_setTempoChange(long jarg1, SoundTouch jarg1_, float jarg2);
  public final static native void SoundTouch_setPitch(long jarg1, SoundTouch jarg1_, float jarg2);
  public final static native void SoundTouch_setPitchOctaves(long jarg1, SoundTouch jarg1_, float jarg2);
  public final static native void SoundTouch_setPitchSemiTones__SWIG_0(long jarg1, SoundTouch jarg1_, int jarg2);
  public final static native void SoundTouch_setPitchSemiTones__SWIG_1(long jarg1, SoundTouch jarg1_, float jarg2);
  public final static native void SoundTouch_setChannels(long jarg1, SoundTouch jarg1_, long jarg2);
  public final static native void SoundTouch_setSampleRate(long jarg1, SoundTouch jarg1_, long jarg2);
  public final static native void SoundTouch_flush(long jarg1, SoundTouch jarg1_);
  public final static native void SoundTouch_putSamples(long jarg1, SoundTouch jarg1_, long jarg2, long jarg3);
  public final static native void SoundTouch_clear(long jarg1, SoundTouch jarg1_);
  public final static native long SoundTouch_setSetting(long jarg1, SoundTouch jarg1_, int jarg2, int jarg3);
  public final static native int SoundTouch_getSetting(long jarg1, SoundTouch jarg1_, int jarg2);
  public final static native long SoundTouch_numUnprocessedSamples(long jarg1, SoundTouch jarg1_);
  public final static native int BUFF_SIZE_get();
  public final static native long new_RobotAudio(String jarg1, String jarg2);
  public final static native int RobotAudio_pitchShift(long jarg1, RobotAudio jarg1_, float jarg2);
  public final static native void delete_RobotAudio(long jarg1);
}
