/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.polysfactory.robotaudio.jni;

public class SoundTouch {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SoundTouch(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SoundTouch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeSoundTouchJNI.delete_SoundTouch(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SoundTouch() {
    this(NativeSoundTouchJNI.new_SoundTouch(), true);
  }

  public static String getVersionString() {
    return NativeSoundTouchJNI.SoundTouch_getVersionString();
  }

  public static SWIGTYPE_p_uint getVersionId() {
    return new SWIGTYPE_p_uint(NativeSoundTouchJNI.SoundTouch_getVersionId(), true);
  }

  public void setRate(float newRate) {
    NativeSoundTouchJNI.SoundTouch_setRate(swigCPtr, this, newRate);
  }

  public void setTempo(float newTempo) {
    NativeSoundTouchJNI.SoundTouch_setTempo(swigCPtr, this, newTempo);
  }

  public void setRateChange(float newRate) {
    NativeSoundTouchJNI.SoundTouch_setRateChange(swigCPtr, this, newRate);
  }

  public void setTempoChange(float newTempo) {
    NativeSoundTouchJNI.SoundTouch_setTempoChange(swigCPtr, this, newTempo);
  }

  public void setPitch(float newPitch) {
    NativeSoundTouchJNI.SoundTouch_setPitch(swigCPtr, this, newPitch);
  }

  public void setPitchOctaves(float newPitch) {
    NativeSoundTouchJNI.SoundTouch_setPitchOctaves(swigCPtr, this, newPitch);
  }

  public void setPitchSemiTones(int newPitch) {
    NativeSoundTouchJNI.SoundTouch_setPitchSemiTones__SWIG_0(swigCPtr, this, newPitch);
  }

  public void setPitchSemiTones(float newPitch) {
    NativeSoundTouchJNI.SoundTouch_setPitchSemiTones__SWIG_1(swigCPtr, this, newPitch);
  }

  public void setChannels(SWIGTYPE_p_uint numChannels) {
    NativeSoundTouchJNI.SoundTouch_setChannels(swigCPtr, this, SWIGTYPE_p_uint.getCPtr(numChannels));
  }

  public void setSampleRate(SWIGTYPE_p_uint srate) {
    NativeSoundTouchJNI.SoundTouch_setSampleRate(swigCPtr, this, SWIGTYPE_p_uint.getCPtr(srate));
  }

  public void flush() {
    NativeSoundTouchJNI.SoundTouch_flush(swigCPtr, this);
  }

  public void putSamples(SWIGTYPE_p_SAMPLETYPE samples, SWIGTYPE_p_uint numSamples) {
    NativeSoundTouchJNI.SoundTouch_putSamples(swigCPtr, this, SWIGTYPE_p_SAMPLETYPE.getCPtr(samples), SWIGTYPE_p_uint.getCPtr(numSamples));
  }

  public void clear() {
    NativeSoundTouchJNI.SoundTouch_clear(swigCPtr, this);
  }

  public SWIGTYPE_p_BOOL setSetting(int settingId, int value) {
    return new SWIGTYPE_p_BOOL(NativeSoundTouchJNI.SoundTouch_setSetting(swigCPtr, this, settingId, value), true);
  }

  public int getSetting(int settingId) {
    return NativeSoundTouchJNI.SoundTouch_getSetting(swigCPtr, this, settingId);
  }

  public SWIGTYPE_p_uint numUnprocessedSamples() {
    return new SWIGTYPE_p_uint(NativeSoundTouchJNI.SoundTouch_numUnprocessedSamples(swigCPtr, this), true);
  }

}
