/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.polysfactory.robotaudio.jni;

public class SWIGTYPE_p_uint {
  private long swigCPtr;

  protected SWIGTYPE_p_uint(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_uint() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_uint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

