

audio: AAFilter.o BPMDetect.o FIFOSampleBuffer.o FIRFilter.o PeakFinder.o RateTransposer.o RobotAudio.o SoundTouch.o TDStretch.o WavFile.o cpu_detect_x86_gcc.o mmx_optimized.o sse_optimized.o
	g++ -o audio AAFilter.o BPMDetect.o FIFOSampleBuffer.o FIRFilter.o PeakFinder.o RateTransposer.o RobotAudio.o SoundTouch.o TDStretch.o WavFile.o cpu_detect_x86_gcc.o mmx_optimized.o sse_optimized.o
 AAFilter.o: AAFilter.cpp
	g++ -c AAFilter.cpp -o AAFilter.o 
 BPMDetect.o: BPMDetect.cpp
	g++ -c BPMDetect.cpp -o BPMDetect.o 
 FIFOSampleBuffer.o: FIFOSampleBuffer.cpp
	g++ -c FIFOSampleBuffer.cpp -o FIFOSampleBuffer.o 
 FIRFilter.o: FIRFilter.cpp
	g++ -c FIRFilter.cpp -o FIRFilter.o 
 PeakFinder.o: PeakFinder.cpp
	g++ -c PeakFinder.cpp -o PeakFinder.o 
 RateTransposer.o: RateTransposer.cpp
	g++ -c RateTransposer.cpp -o RateTransposer.o 
 RobotAudio.o: RobotAudio.cpp
	g++ -c RobotAudio.cpp -o RobotAudio.o 
 SoundTouch.o: SoundTouch.cpp
	g++ -c SoundTouch.cpp -o SoundTouch.o 
 TDStretch.o: TDStretch.cpp
	g++ -c TDStretch.cpp -o TDStretch.o 
 WavFile.o: WavFile.cpp
	g++ -c WavFile.cpp -o WavFile.o 
 cpu_detect_x86_gcc.o: cpu_detect_x86_gcc.cpp
	g++ -c cpu_detect_x86_gcc.cpp -o cpu_detect_x86_gcc.o 
 mmx_optimized.o: mmx_optimized.cpp
	g++ -c mmx_optimized.cpp -o mmx_optimized.o 
 sse_optimized.o: sse_optimized.cpp
	g++ -c sse_optimized.cpp -o sse_optimized.o